Fixed an error in updating tag
javax.persistence.PersistenceException: org.hibernate.HibernateException:
A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: models.Tag.postTagsA collection with cascade="all-delete-orphan" was no longer referenced